import pytest

from sbom_embedded.parsers.buildroot import (
    BuildrootParseError,
    find_manifest,
    parse,
    parse_manifest_csv,
)


def test_reads_a_fully_quoted_manifest(fixtures):
    components, label = parse(fixtures / "buildroot-2023.02")
    assert label == "buildroot"
    # Build order, not alphabetical -- Buildroot appends as packages finish.
    assert [c.name for c in components] == [
        "glibc",
        "linux-headers",
        "busybox",
        "rpi-firmware",
        "linux",
    ]


def test_reads_a_minimally_quoted_crlf_manifest(fixtures):
    # Buildroot quotes a field only when it contains a comma, and real files
    # in the wild carry CRLF endings. Neither may reach the parsed values.
    components, _ = parse(fixtures / "buildroot-minimal-quoting")
    assert len(components) == 92
    assert all("\r" not in c.name for c in components)
    attr = next(c for c in components if c.name == "attr")
    assert attr.license == "GPL-2.0+ (programs), LGPL-2.1+ (libraries)"


def test_a_comma_inside_a_quoted_license_is_not_a_column_break(fixtures):
    components, _ = parse(fixtures / "buildroot-2023.02")
    glibc = next(c for c in components if c.name == "glibc")
    assert glibc.license == (
        "GPL-2.0+ (programs), LGPL-2.1+, BSD-3-Clause, MIT (library)"
    )


def test_the_custom_version_placeholder_is_not_treated_as_a_version(fixtures):
    # Buildroot writes "custom" when the source is a local tarball or a git
    # revision, i.e. when it has no version. "pkg:generic/linux@custom" would
    # be a fabricated version string.
    components, _ = parse(fixtures / "buildroot-2023.02")
    linux = next(c for c in components if c.name == "linux")
    assert linux.version is None
    assert linux.purl == "pkg:generic/linux"


def test_the_unknown_license_placeholder_becomes_no_license(fixtures):
    components, _ = parse(fixtures / "buildroot-minimal-quoting")
    toolchain = next(c for c in components if c.name.startswith("toolchain-external"))
    assert toolchain.license is None


def test_columns_are_found_by_name_so_older_layouts_still_parse(tmp_path):
    # A pre-2018.11 manifest has six columns: no DEPENDENCIES WITH LICENSES.
    manifest = tmp_path / "manifest.csv"
    manifest.write_text(
        '"PACKAGE","VERSION","LICENSE","LICENSE FILES","SOURCE ARCHIVE","SOURCE SITE"\n'
        '"uclibc","1.0.22","LGPLv2.1+","COPYING.LIB","uClibc-ng-1.0.22.tar.xz",'
        '"http://downloads.uclibc-ng.org/releases/1.0.22"\n'
    )
    components = parse_manifest_csv(manifest)
    assert [(c.name, c.version, c.license) for c in components] == [
        ("uclibc", "1.0.22", "LGPLv2.1+")
    ]


def test_the_manifest_is_found_from_either_directory_level(fixtures):
    output_dir = fixtures / "buildroot-2023.02"
    assert find_manifest(output_dir).name == "manifest.csv"
    assert find_manifest(output_dir / "legal-info").name == "manifest.csv"
    assert find_manifest(output_dir / "legal-info" / "manifest.csv").name == (
        "manifest.csv"
    )


def test_host_packages_are_not_read(fixtures):
    # host-manifest.csv holds ccache, pkgconf and friends. They build the
    # firmware; they are not in it.
    components, _ = parse(fixtures / "buildroot-minimal-quoting")
    assert not [c for c in components if c.name.startswith("host-")]


def test_a_missing_manifest_is_reported(tmp_path):
    with pytest.raises(BuildrootParseError, match=r"no manifest\.csv"):
        parse(tmp_path)


def test_a_header_without_a_package_column_is_rejected(tmp_path):
    manifest = tmp_path / "manifest.csv"
    manifest.write_text("NAME,VERSION\nfoo,1.0\n")
    with pytest.raises(BuildrootParseError, match="no PACKAGE column"):
        parse_manifest_csv(manifest)


def test_a_host_manifest_sitting_beside_the_target_one_is_not_read(tmp_path):
    # The previous coverage could not fail: no fixture has a host-manifest.csv
    # and no target manifest has a host- row, so nothing was excluded.
    legal = tmp_path / "legal-info"
    legal.mkdir()
    header = '"PACKAGE","VERSION","LICENSE"\n'
    (legal / "manifest.csv").write_text(header + '"busybox","1.36.1","GPL-2.0"\n')
    (legal / "host-manifest.csv").write_text(
        header + '"host-pkgconf","1.9.5","ISC"\n"buildroot","2023.02","GPL-2.0+"\n'
    )
    components, _ = parse(tmp_path)
    assert [c.name for c in components] == ["busybox"]


def test_a_row_too_short_to_reach_license_is_rejected(tmp_path):
    manifest = tmp_path / "manifest.csv"
    manifest.write_text('"PACKAGE","VERSION","LICENSE"\n"busybox","1.36.1"\n')
    with pytest.raises(BuildrootParseError, match="at least 3 columns"):
        parse_manifest_csv(manifest)


def test_a_current_release_manifest_from_a_real_build(fixtures):
    # Generated by running `make legal-info` on Buildroot 2026.08-rc3 on the
    # development machine; see PROVENANCE.md.
    components, _ = parse(fixtures / "buildroot-2026.08")
    assert len(components) == 44
    assert all(c.version for c in components)
    assert all(c.license for c in components)


def test_a_long_license_with_nested_parentheses_survives_intact(fixtures):
    # A real glibc row: 296 characters, commas inside parentheses, the lot.
    # Any attempt to split it on commas would shred it.
    components, _ = parse(fixtures / "buildroot-2026.08")
    glibc = next(c for c in components if c.name == "glibc")
    assert len(glibc.license) == 296
    assert glibc.license.startswith("GPL-2.0+ (programs), LGPL-2.1+,")
    assert glibc.license.endswith("GFDL-1.3-or-later (manual)")
    assert glibc.version == "2.44-36-g2d5421ffca8893534d5e02ad38c28acd8e778fa3"


def test_unusual_upstream_version_forms_are_not_mangled(fixtures):
    components, _ = parse(fixtures / "buildroot-2026.08")
    by_name = {c.name: c.version for c in components}
    assert by_name["sudo"] == "1.9.17p2"
    assert by_name["openssh"] == "10.5p1"
    assert by_name["ncurses"] == "6.6-20251231"
